version: '3'

services:
  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recommendation
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo:5.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: recommendation
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  
  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      SERVICES: sqs
    ports:
      - "4566:4566"
    volumes:
      - ./localstack/localstack-setup.sh:/etc/localstack/init/ready.d/script.sh

volumes:
  postgres-data:
  mongo-data: